# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor_pvt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='monitor_pvt.proto',
  package='gnss_sdr',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11monitor_pvt.proto\x12\x08gnss_sdr\"\x86\x04\n\nMonitorPvt\x12 \n\x18tow_at_current_symbol_ms\x18\x01 \x01(\r\x12\x0c\n\x04week\x18\x02 \x01(\r\x12\x0f\n\x07rx_time\x18\x03 \x01(\x01\x12\x17\n\x0fuser_clk_offset\x18\x04 \x01(\x01\x12\r\n\x05pos_x\x18\x05 \x01(\x01\x12\r\n\x05pos_y\x18\x06 \x01(\x01\x12\r\n\x05pos_z\x18\x07 \x01(\x01\x12\r\n\x05vel_x\x18\x08 \x01(\x01\x12\r\n\x05vel_y\x18\t \x01(\x01\x12\r\n\x05vel_z\x18\n \x01(\x01\x12\x0e\n\x06\x63ov_xx\x18\x0b \x01(\x01\x12\x0e\n\x06\x63ov_yy\x18\x0c \x01(\x01\x12\x0e\n\x06\x63ov_zz\x18\r \x01(\x01\x12\x0e\n\x06\x63ov_xy\x18\x0e \x01(\x01\x12\x0e\n\x06\x63ov_yz\x18\x0f \x01(\x01\x12\x0e\n\x06\x63ov_zx\x18\x10 \x01(\x01\x12\x10\n\x08latitude\x18\x11 \x01(\x01\x12\x11\n\tlongitude\x18\x12 \x01(\x01\x12\x0e\n\x06height\x18\x13 \x01(\x01\x12\x12\n\nvalid_sats\x18\x14 \x01(\r\x12\x17\n\x0fsolution_status\x18\x15 \x01(\r\x12\x15\n\rsolution_type\x18\x16 \x01(\r\x12\x17\n\x0f\x61r_ratio_factor\x18\x17 \x01(\x02\x12\x1a\n\x12\x61r_ratio_threshold\x18\x18 \x01(\x02\x12\x0c\n\x04gdop\x18\x19 \x01(\x01\x12\x0c\n\x04pdop\x18\x1a \x01(\x01\x12\x0c\n\x04hdop\x18\x1b \x01(\x01\x12\x0c\n\x04vdop\x18\x1c \x01(\x01\x62\x06proto3')
)




_MONITORPVT = _descriptor.Descriptor(
  name='MonitorPvt',
  full_name='gnss_sdr.MonitorPvt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tow_at_current_symbol_ms', full_name='gnss_sdr.MonitorPvt.tow_at_current_symbol_ms', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='week', full_name='gnss_sdr.MonitorPvt.week', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rx_time', full_name='gnss_sdr.MonitorPvt.rx_time', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_clk_offset', full_name='gnss_sdr.MonitorPvt.user_clk_offset', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos_x', full_name='gnss_sdr.MonitorPvt.pos_x', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos_y', full_name='gnss_sdr.MonitorPvt.pos_y', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos_z', full_name='gnss_sdr.MonitorPvt.pos_z', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vel_x', full_name='gnss_sdr.MonitorPvt.vel_x', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vel_y', full_name='gnss_sdr.MonitorPvt.vel_y', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vel_z', full_name='gnss_sdr.MonitorPvt.vel_z', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cov_xx', full_name='gnss_sdr.MonitorPvt.cov_xx', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cov_yy', full_name='gnss_sdr.MonitorPvt.cov_yy', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cov_zz', full_name='gnss_sdr.MonitorPvt.cov_zz', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cov_xy', full_name='gnss_sdr.MonitorPvt.cov_xy', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cov_yz', full_name='gnss_sdr.MonitorPvt.cov_yz', index=14,
      number=15, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cov_zx', full_name='gnss_sdr.MonitorPvt.cov_zx', index=15,
      number=16, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='gnss_sdr.MonitorPvt.latitude', index=16,
      number=17, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='gnss_sdr.MonitorPvt.longitude', index=17,
      number=18, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='gnss_sdr.MonitorPvt.height', index=18,
      number=19, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valid_sats', full_name='gnss_sdr.MonitorPvt.valid_sats', index=19,
      number=20, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='solution_status', full_name='gnss_sdr.MonitorPvt.solution_status', index=20,
      number=21, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='solution_type', full_name='gnss_sdr.MonitorPvt.solution_type', index=21,
      number=22, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ar_ratio_factor', full_name='gnss_sdr.MonitorPvt.ar_ratio_factor', index=22,
      number=23, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ar_ratio_threshold', full_name='gnss_sdr.MonitorPvt.ar_ratio_threshold', index=23,
      number=24, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gdop', full_name='gnss_sdr.MonitorPvt.gdop', index=24,
      number=25, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pdop', full_name='gnss_sdr.MonitorPvt.pdop', index=25,
      number=26, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hdop', full_name='gnss_sdr.MonitorPvt.hdop', index=26,
      number=27, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vdop', full_name='gnss_sdr.MonitorPvt.vdop', index=27,
      number=28, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=550,
)

DESCRIPTOR.message_types_by_name['MonitorPvt'] = _MONITORPVT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MonitorPvt = _reflection.GeneratedProtocolMessageType('MonitorPvt', (_message.Message,), dict(
  DESCRIPTOR = _MONITORPVT,
  __module__ = 'monitor_pvt_pb2'
  # @@protoc_insertion_point(class_scope:gnss_sdr.MonitorPvt)
  ))
_sym_db.RegisterMessage(MonitorPvt)


# @@protoc_insertion_point(module_scope)
