# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gnss_synchro.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gnss_synchro.proto',
  package='gnss_sdr',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12gnss_synchro.proto\x12\x08gnss_sdr\"\x96\x05\n\x0bGnssSynchro\x12\x0e\n\x06system\x18\x01 \x01(\t\x12\x0e\n\x06signal\x18\x02 \x01(\t\x12\x0b\n\x03prn\x18\x03 \x01(\r\x12\x12\n\nchannel_id\x18\x04 \x01(\x05\x12\x19\n\x11\x61\x63q_delay_samples\x18\x05 \x01(\x01\x12\x16\n\x0e\x61\x63q_doppler_hz\x18\x06 \x01(\x01\x12\x1f\n\x17\x61\x63q_samplestamp_samples\x18\x07 \x01(\x04\x12\x18\n\x10\x61\x63q_doppler_step\x18\x08 \x01(\r\x12\x1e\n\x16\x66lag_valid_acquisition\x18\t \x01(\x08\x12\n\n\x02\x66s\x18\n \x01(\x03\x12\x10\n\x08prompt_i\x18\x0b \x01(\x01\x12\x10\n\x08prompt_q\x18\x0c \x01(\x01\x12\x11\n\tcn0_db_hz\x18\r \x01(\x01\x12\x1a\n\x12\x63\x61rrier_doppler_hz\x18\x0e \x01(\x01\x12\x1a\n\x12\x63\x61rrier_phase_rads\x18\x0f \x01(\x01\x12\x1a\n\x12\x63ode_phase_samples\x18\x10 \x01(\x01\x12\x1f\n\x17tracking_sample_counter\x18\x11 \x01(\x04\x12 \n\x18\x66lag_valid_symbol_output\x18\x12 \x01(\x08\x12\x1d\n\x15\x63orrelation_length_ms\x18\x13 \x01(\x05\x12\x17\n\x0f\x66lag_valid_word\x18\x14 \x01(\x08\x12 \n\x18tow_at_current_symbol_ms\x18\x15 \x01(\r\x12\x15\n\rpseudorange_m\x18\x16 \x01(\x01\x12\x0f\n\x07rx_time\x18\x17 \x01(\x01\x12\x1e\n\x16\x66lag_valid_pseudorange\x18\x18 \x01(\x08\x12\x15\n\rinterp_tow_ms\x18\x19 \x01(\x01\x12%\n\x1d\x66lag_PLL_180_deg_phase_locked\x18\x1a \x01(\x08\"8\n\x0bObservables\x12)\n\nobservable\x18\x01 \x03(\x0b\x32\x15.gnss_sdr.GnssSynchrob\x06proto3')
)




_GNSSSYNCHRO = _descriptor.Descriptor(
  name='GnssSynchro',
  full_name='gnss_sdr.GnssSynchro',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='system', full_name='gnss_sdr.GnssSynchro.system', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signal', full_name='gnss_sdr.GnssSynchro.signal', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prn', full_name='gnss_sdr.GnssSynchro.prn', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel_id', full_name='gnss_sdr.GnssSynchro.channel_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acq_delay_samples', full_name='gnss_sdr.GnssSynchro.acq_delay_samples', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acq_doppler_hz', full_name='gnss_sdr.GnssSynchro.acq_doppler_hz', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acq_samplestamp_samples', full_name='gnss_sdr.GnssSynchro.acq_samplestamp_samples', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acq_doppler_step', full_name='gnss_sdr.GnssSynchro.acq_doppler_step', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flag_valid_acquisition', full_name='gnss_sdr.GnssSynchro.flag_valid_acquisition', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fs', full_name='gnss_sdr.GnssSynchro.fs', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prompt_i', full_name='gnss_sdr.GnssSynchro.prompt_i', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prompt_q', full_name='gnss_sdr.GnssSynchro.prompt_q', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cn0_db_hz', full_name='gnss_sdr.GnssSynchro.cn0_db_hz', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='carrier_doppler_hz', full_name='gnss_sdr.GnssSynchro.carrier_doppler_hz', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='carrier_phase_rads', full_name='gnss_sdr.GnssSynchro.carrier_phase_rads', index=14,
      number=15, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code_phase_samples', full_name='gnss_sdr.GnssSynchro.code_phase_samples', index=15,
      number=16, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tracking_sample_counter', full_name='gnss_sdr.GnssSynchro.tracking_sample_counter', index=16,
      number=17, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flag_valid_symbol_output', full_name='gnss_sdr.GnssSynchro.flag_valid_symbol_output', index=17,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='correlation_length_ms', full_name='gnss_sdr.GnssSynchro.correlation_length_ms', index=18,
      number=19, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flag_valid_word', full_name='gnss_sdr.GnssSynchro.flag_valid_word', index=19,
      number=20, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tow_at_current_symbol_ms', full_name='gnss_sdr.GnssSynchro.tow_at_current_symbol_ms', index=20,
      number=21, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pseudorange_m', full_name='gnss_sdr.GnssSynchro.pseudorange_m', index=21,
      number=22, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rx_time', full_name='gnss_sdr.GnssSynchro.rx_time', index=22,
      number=23, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flag_valid_pseudorange', full_name='gnss_sdr.GnssSynchro.flag_valid_pseudorange', index=23,
      number=24, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interp_tow_ms', full_name='gnss_sdr.GnssSynchro.interp_tow_ms', index=24,
      number=25, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flag_PLL_180_deg_phase_locked', full_name='gnss_sdr.GnssSynchro.flag_PLL_180_deg_phase_locked', index=25,
      number=26, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=695,
)


_OBSERVABLES = _descriptor.Descriptor(
  name='Observables',
  full_name='gnss_sdr.Observables',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='observable', full_name='gnss_sdr.Observables.observable', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=697,
  serialized_end=753,
)

_OBSERVABLES.fields_by_name['observable'].message_type = _GNSSSYNCHRO
DESCRIPTOR.message_types_by_name['GnssSynchro'] = _GNSSSYNCHRO
DESCRIPTOR.message_types_by_name['Observables'] = _OBSERVABLES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GnssSynchro = _reflection.GeneratedProtocolMessageType('GnssSynchro', (_message.Message,), dict(
  DESCRIPTOR = _GNSSSYNCHRO,
  __module__ = 'gnss_synchro_pb2'
  # @@protoc_insertion_point(class_scope:gnss_sdr.GnssSynchro)
  ))
_sym_db.RegisterMessage(GnssSynchro)

Observables = _reflection.GeneratedProtocolMessageType('Observables', (_message.Message,), dict(
  DESCRIPTOR = _OBSERVABLES,
  __module__ = 'gnss_synchro_pb2'
  # @@protoc_insertion_point(class_scope:gnss_sdr.Observables)
  ))
_sym_db.RegisterMessage(Observables)


# @@protoc_insertion_point(module_scope)
